<table style="height: 530px; width: 618px;" border="1">
    <tbody>
        <tr style="height: 28px;">
            <td style="background-color: #006a9e; height: 28px; width: 719px;" colspan="4">&nbsp;<strong><img src="http://schoeler.com.br/imagens/logo-email.png" /></strong></td>
        </tr>
        <tr style="height: 29px;">
            <td style="width: 719px; height: 29px;" colspan="4">
                <h4><strong>Ol&aacute; <?= utf8_decode($this->dados['nome_usuario']); ?></strong></h4>
            </td>
        </tr>
        <tr style="height: 7px;">
            <td style="width: 719px; height: 7px; background-color: #006a9e;" colspan="4">
                <h3><span style="color: #ffffff;">Segue os dados da pesagem do ve&iacute;culo:&nbsp;<?= $this->dados['veiculo']; ?></span></h3>
            </td>
        </tr>
        <tr style="height: 50px;">
            <td style="background-color: #f2f2f2; width: 203px; height: 50px;">
                <p>&nbsp;<strong>Motorista:</strong></p>
            </td>
            <td style="background-color: #f2f2f2; width: 157px; height: 50px;">&nbsp;<?= utf8_decode($this->dados['motorista']); ?></td>
            <td style="background-color: #f2f2f2; width: 209px; height: 50px;"><strong>&nbsp;Categoria:</strong></td>
            <td style="background-color: #f2f2f2; width: 150px; height: 50px;">&nbsp;<?= utf8_decode($this->dados['categoria']); ?></td>
        </tr>
        <tr style="height: 18px;">
            <td style="width: 203px; height: 18px;">
                <p>&nbsp;<strong>Subcategoria:</strong></p>
            </td>
            <td style="width: 157px; height: 18px;">&nbsp;<?= utf8_decode($this->dados['subcategoria']); ?></td>
            <td style="width: 209px; height: 18px;"><strong>Origem Viagem:</strong></td>
            <td style="width: 150px; height: 18px;">&nbsp;<?= utf8_decode($this->dados['origem']); ?></td>
        </tr>
        <tr style="height: 18px;">
            <td style="width: 203px; height: 18px;">
                <p><strong>Origem Carregamento:</strong></p>
            </td>
            <td style="width: 157px; height: 18px;">&nbsp;<?= utf8_decode($this->dados['origem_carregamento']); ?></td>
            <td style="width: 209px; height: 18px;"><strong>Destino Carregamento:</strong></td>
            <td style="width: 150px; height: 18px;">&nbsp;<?= utf8_decode($this->dados['destino_carregamento']); ?></td>
        </tr>
        <tr style="height: 51px;">
            <td style="width: 203px; height: 51px; background-color: #f2f2f2;">
                <p><strong>Destino Final:</strong></p>
            </td>
            <td style="width: 157px; height: 51px; background-color: #f2f2f2;">&nbsp;<?= utf8_decode($this->dados['destino_final']); ?></td>
            <td style="background-color: #f2f2f2; width: 209px; height: 51px;">&nbsp;<strong>Tipo Abertura:</strong></td>
            <td style="background-color: #f2f2f2; width: 150px; height: 51px;">&nbsp;<?= utf8_decode($this->dados['pesagem_manual_inicio']); ?></td>
        </tr>
        <tr style="height: 18px;">
            <td style="width: 203px; height: 18px;">
                <p><strong>Tipo Fechamento:</strong></p>
            </td>
            <td style="width: 157px; height: 18px;">&nbsp;<?= utf8_decode($this->dados['pesagem_manual_fim']); ?></td>
            <td style="width: 209px; height: 18px;"><strong>Local Pes. Abertura:</strong></td>
            <td style="width: 150px; height: 18px;">&nbsp;<?= utf8_decode($this->dados['local_abertura']); ?></td>
        </tr>
        <tr style="height: 18px; background-color: #f2f2f2;">
            <td style="background-color: #f2f2f2; width: 203px; height: 18px;">
                <p><strong>Local Pes. Fechamento:</strong></p>
            </td>
            <td style="background-color: #f2f2f2; width: 157px; height: 18px;">&nbsp;<?= utf8_decode($this->dados['local_fechamento']); ?></td>
            <td style="background-color: #f2f2f2; width: 209px; height: 18px;"><strong>Peso Bruto:</strong></td>
            <td style="background-color: #f2f2f2; width: 150px; height: 18px;">&nbsp;<?= $this->dados['peso_bruto']; ?></td>
        </tr>
        <tr style="height: 18px;">
            <td style="width: 203px; height: 18px;">
                <p><strong>Peso Tara:</strong></p>
            </td>
            <td style="width: 157px; height: 18px;">&nbsp;<?= $this->dados['peso_tara']; ?></td>
            <td style="width: 209px; height: 18px;"><strong>Peso Liqu&iacute;do:</strong></td>
            <td style="width: 150px; height: 18px;">&nbsp;<?= $this->dados['peso_liquido']; ?></td>
        </tr>
        <tr style="height: 18px;">
            <td style="width: 203px; height: 18px;">
                <p><strong>Peso M&eacute;dio:</strong></p>
            </td>
            <td style="width: 157px; height: 18px;">&nbsp;<?= $this->dados['peso_medio']; ?></td>
            <td style="width: 209px; height: 18px;"><strong>Quantidade:</strong></td>
            <td style="width: 150px; height: 18px;">&nbsp;<?= $this->dados['quantidade']; ?></td>
        </tr>
        <tr style="height: 18px;">
            <td style="width: 203px; height: 18px;">
                <p><strong>Data Abertura:</strong></p>
            </td>
            <td style="width: 157px; height: 18px;">&nbsp;<?= $this->dados['data_abertura']; ?></td>
            <td style="width: 209px; height: 18px;"><strong>Data Fechamento:</strong></td>
            <td style="width: 150px; height: 18px;">&nbsp;<?= $this->dados['data_fechamento']; ?></td>
        </tr>
        <tr style="height: 18px;">
            <td style="width: 203px; height: 18px;">
                <p><strong>Observa&ccedil;&atilde;o:</strong></p>
            </td>
            <td style="width: 516px; height: 18px;" colspan="3"><?= utf8_decode($this->dados['observacao']); ?></td>
        </tr>
        <tr style="height: 18px; background-color: #f2f2f2;">
            <td style="width: 719px; height: 18px;" colspan="4">&nbsp;</td>
        </tr>
        <tr style="height: 53px;">
            <td style="width: 719px; height: 53px; background-color: #006a9e;" colspan="4">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        </tr>
    </tbody>
</table>
