<style>
   .credit a {
        color: #eeeeee!important;
        text-decoration: none!important;
    }
        .credit a:hover, .credit a:focus {
        color: #8E8686!important;
         text-decoration: none!important;
    }
</style>
<div id="footer" style="background-color: #<?=$this->conf['cor_layout'];?>">
   <div class="container">
     <p class="muted credit">SysControl - desenvolvido por: <a href="http://www.thiagocarlos.com.br" target="new">Thiago Carlos</a></p>
   </div>
</div>