<html xmlns="http://www.w3c.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- GOOGLE FONTS-->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
        <?= $this->headMeta(); ?>
       
        <link href="<?= $this->BaseUrl('adm/default/css/bootstrap.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->BaseUrl('adm/default/css/font-awesome.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->BaseUrl('adm/default/css/custom.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->BaseUrl('adm/default/js/lib/fancybox/source/jquery.fancybox.css?v=2.1.5'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->BaseUrl('adm/default/css/jquery.nice-file-input.min.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
        <link href="<?= $this->BaseUrl('adm/default/js/dataTables/dataTables.bootstrap.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->BaseUrl('adm/default/css/select2.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->BaseUrl('adm/default/css/select2-bootstrap.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->BaseUrl('adm/default/css/select2.css'); ?>" rel="stylesheet" media="screen" type="text/css" />
        <?= $this->headLink(); ?>
        
        <script src="<?= $this->BaseUrl('adm/default/js/jquery1.7.2.min.js'); ?>" type="text/javascript"></script>
        <script src="<?= $this->BaseUrl('adm/default/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
        <script src="<?= $this->BaseUrl('adm/default/js/jquery.metisMenu.js'); ?>" type="text/javascript"></script>
        <script src="<?= $this->BaseUrl('adm/default/js/morris/raphael-2.1.0.min.js'); ?>" type="text/javascript"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
        <script src="<?= $this->BaseUrl('adm/default/js/bootstrap-filestyle.min.js'); ?>" type="text/javascript"></script>
        <script src="<?= $this->BaseUrl('adm/default/js/lib/ckeditor/ckeditor.js'); ?>" type="text/javascript"></script>
        <?= $this->headScript(); ?>
    </head>
    <body>
       <?= $this->FlashMessenger(); ?>
       <?= $this->layout()->content; ?>        
    </body>
</html>