<?
$this->headScript()->appendFile($this->BaseUrl('adm/default/js/FormMotorista.js'));
?>
<div class="row">
    <div class="col-md-10">
        <!-- Form Elements -->
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Cadastro de Motorista</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10">
                        <?php echo $this->form; ?>
                    </div>                 
                </div>
            </div>
        </div>
        <!-- End Form Elements -->
    </div>
</div>
