<?
$this->headScript()->appendFile($this->BaseUrl('adm/default/js/FormCombustivel.js'));
$this->headLink()->appendStylesheet($this->BaseUrl('adm/default/css/FormCombustivel.css'));
?>
<div class="row">
    <div class="col-md-8">
        <!-- Form Elements -->
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Entrada de Combustivel</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10">
                        <?php echo $this->form; ?>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Form Elements -->
    </div>
    
    <?
    $porcentagem_Aberto = $this->Porcentagem($this->estoque, $this->capacidade);
    
    $var1 = 20;
    $var2 = 40;
    $var3 = 80;
    $var4 = 100;
     
    if($porcentagem_Aberto <= $var1){
        $class = 'danger';
    }else if($porcentagem_Aberto <= $var2){
        $class = 'warning';
    }else if($porcentagem_Aberto <= $var3){
        $class = 'info';
    }else{
        $class = 'success';
    }
    
    ?>
    
    
    <div class="col-md-4">
        <!-- Form Elements -->
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Estoque de Combustivel</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12" align="center">
                        <div class="progress vertical">
                          <div class="progress-bar progress-bar-<?=$class;?>" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: <?=$porcentagem_Aberto;?>%;">
                              <p class="text-center"><?=$porcentagem_Aberto;?>%</p>
                        </div>  
                        </div>
                        <div class="alert alert-info" role="alert">Seu estoque atual é de: <?=number_format($this->estoque, 2, ",", ".");?> litros.</div>


                    </div>
                </div>
            </div>
        </div>
    </div>
        </div>
        <!-- End Form Elements -->
    </div>
</div>
