<?
$this->headLink()->appendStylesheet($this->BaseUrl('adm/default/css/ticket.css'));
$this->headScript()->appendFile($this->BaseUrl('adm/default/js/ticket.js'));
?>

<div class="row">
    <div id="conteudo" class="col-md-12">
        <!-- Form Elements -->
        <div class="panel panel-primary tbticket">
            <div class="panel-heading">
                <h2 class="panel-title">Controle de Pesagem de Suinos Schoeler Agropecuária LTDA-E</h2>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <table width="1179" border="0" class="table ticket param" data-id="<?= $this->dados['id']; ?>">
                            <thead class="ticket">
                                <tr>
                                    <th width="21%"><img src="<?= $this->BaseUrl('adm/default/img/logo.jpg'); ?>" class="img-rounded" alt="Schoeler Suínos" width="140" height="82"></th>                                 <th colspan="3">

                                        <div style="font-size:14px;color:#191412;" align="right">Data e Hora Pesagem:
                                            <?= $this->dados['data_entrada']; ?>
                                        </div>
                                        <div style="font-size:14px;color:#191412;"   align="right">Data e Hora Emissão:
                                            <?= date('d/m/Y H:i:s'); ?>
                                        </div></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="2">
                                        <p align="left"><strong>Produto:</strong>
                                            <?= $this->dados['nome_categoria']; ?>
                                            <? if (!empty($this->dados['nome_subcategoria'])) {
                                                echo '/ ' . $this->dados['nome_subcategoria'];
                                            }
                                            ?>
                                        </p></td>
                                    <td colspan="3"><p align="right"><strong>Veiculo:</strong>
                                            <?= $this->dados['modelo']; ?>
                                            /
<?= $this->dados['placa']; ?>
                                        </p></td>
                                </tr>
                                <tr>
                                    <td colspan="2"><div align="left"><strong>Peso Bruto:</strong>
                                            <?= number_format($this->dados['peso_bruto'], 2, ".", ","); ?>
                                        </div></td>
                                    <td colspan="3"><div align="right"><strong>Transportador:</strong>
<?= $this->dados['proprietario']; ?>
                                        </div></td>
                                </tr>
                                <tr>
                                    <td colspan="2"><div align="left"><strong>Peso Tara:</strong>
                                            <?= number_format($this->dados['peso_tara'], 2, ".", ","); ?>
                                        </div></td>
                                    <td colspan="3"><div align="right"><strong>Fornecedor:</strong>
<?= $this->dados['fornecedor']; ?>
                                        </div></td>
                                </tr>

                                <tr>
                                    <td colspan="2"><div align="left"><strong>Peso Liquído:</strong>
                                            <?= number_format($this->dados['peso_liquido'], 2, ".", ","); ?>
                                        </div></td>
                                    <td colspan="3"><div align="right"><strong>Destino:</strong>
<?= $this->dados['cliente']; ?>
                                        </div></td>
                                </tr>

<? if (!empty($this->dados['peso_medio']) && $this->dados['peso_medio'] > 0 && !is_null($this->dados['peso_medio'])) { ?>
                                    <tr>
                                        <td colspan="2"><div align="left"><strong>Peso Médio:</strong> <? echo number_format($this->dados['peso_medio'], 2, ".", ",") . ' - KG / ' . $this->dados['cabecas'] . ' Cabeças'; ?> </div></td>
                                        <td width="5%">&nbsp;</td>
                                        <td width="11%">&nbsp;</td>
                                        <td width="7%">&nbsp;</td>
                                    </tr>
<? } ?>
                                            <? if (!empty($this->dados['descricao'])) { ?>
                                    <tr>
                                        <td colspan="3"><div align="left"><strong>Descrição:</strong>
    <?= nl2br($this->dados['descricao']); ?>
                                            </div></td>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                    </tr>
                                            <? } ?>
                                <tr>
                                    <td colspan="2"><p align="left"><strong>Nota Fiscal:</strong>
<?= $this->dados['nota_fiscal']; ?>
<? if (!empty($this->dados['percentual_quebra'])) { ?>
                                            </p>
                                            <p align="left" style="font-size:14px;"><em>A porcentagem de indice de quebra, está acima de 0.2%</em></p>
                                            <div align="left">
<? } ?>
                                        </div></td>
                                    <td rowspan="2"><p>&nbsp;</p>
                                        <div align="right" id="left-emitente">
                                            <div align="center">
                                                <p><strong>Emitente:</strong>
                                                <?= $this->dados['user']; ?>
                                                </p>
                                                    <? if (!empty($this->dados['cpf_user'])) { ?>
                                                    <p><strong>CPF:</strong>
                                                    <?= $this->dados['cpf_user']; ?>
                                                    </p>
<? } ?>
                                            </div>
                                        </div></td>
                                    <td rowspan="2">&nbsp;</td>
                                    <td rowspan="2"><p>&nbsp;</p>
                                        <div align="right" id="righ-motorista">
                                            <div align="center">
                                                <p><strong>Motorista:</strong>
                                                <?= $this->dados['motorista']; ?>
                                                </p>
                                                    <? if (!empty($this->dados['cpf_motorista'])) { ?>
                                                    <p><strong>CPF:</strong>
                                                    <?= $this->dados['cpf_motorista']; ?>
                                                    </p>
<? } ?>
                                            </div>
                                        </div></td>
                                </tr>
                                <tr>
                                    <td height="21" colspan="2">&nbsp;</td>
                                </tr>

                            </tbody>
                        </table>
                        <div>
                            <div align="right"><strong>
                                    *Obs: O motorista acompanhou a pesagem, e por fim concorda com o que aqui encontra-se expresso.
                                </strong></div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

</div>