<div class="row">
    <div class="col-md-12">
        <!-- Form Elements -->
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Versão do Aplicativo</h3>
            </div>
            <div id="page-inner">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-10">
                            <?= $this->form ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
